---
logging:
  file:
    name: spring.log
    path: ./tmp/
  level:
    root: DEBUG
    com:
      spring:
        demo:
          core: TRACE

spring.security.user.name: user
spring.security.user.password: password

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: none
  application:
    name: demo-base
  data:
    web.pageable.one-indexed-parameters: true

server:
  port: 8080

---
spring:
  application:
    name: demo-local
  config:
    activate:
      on-profile:
        - local
---

