---
logging:
  file:
    name: spring.log
    path: ./tmp/
  level:
    root: DEBUG
    com:
      spring:
        demo:
          core: TRACE

spring:
  datasource:
     url: ""
  application:
    name: demo-base

server:
  port: 8080

---
spring:
  application:
    name: demo-local
  config:
    activate:
      on-profile:
        - local
---
