---
logging:
  file:
    name: spring.log
    path: /tmp/
  level:
    root: DEBUG
    com:
      spring:
        demo:
          core: TRACE

spring:
  sql.init.mode: never
  sql.init.data-locations: classpath:/postgres-data.sql
  sql.init.schema-locations: classpath:/postgres-schema.sql
  security:
    user:
      name: user
      password: password
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:changelog.xml
  data:
    web.pageable.one-indexed-parameters: true
  application:
    name: demo-base

my-application:
  name: demo-app
  authorities: ["user:manage", "user:list"]

server:
  port: 8080

---
spring:
  application:
    name: demo-local
  config:
    activate:
      on-profile:
        - local
---

